Create2019page
IGGG/guntoh-fes pull request #1
Opened 2019-07-22 06:45 UTC by OhataKenji

2019年度版のページを作りました.

[https://iggg.github.io/guntoh-fes/2019](https://iggg.github.io/guntoh-fes/2019)

で行けるようになっています.

内容は随時更新します.

2019-07-22 07:36 UTC, atpons requested changes
2017をまるごと `/2017`に移動して `/` に2019を置けばいいと思った(という話をSlackでしたつもりだった) :bow:
常に最新が `/` に来るようにする．そうすれば，毎年QRコードもURLも使い回せるんだおと思った

2019-07-22 08:03 UTC, atpons commented
と思ったけどなんか自分の言ってることと違ったすみません

2019-10-05 07:59 UTC, matsubara0507 commented
わしも `/2017` を 2017 にして、`/` を 2019 にしてほしいな
まぁまずは `/2019` で作業して概ね完成したら移動するならそれでもいいけど

2019-10-05 08:02 UTC, matsubara0507 commented
ちなみに、手元で動作みた？

2019-10-05 08:02 UTC, matsubara0507 commented
なんか適当にスクショでも貼ってほしい

2019-10-05 08:05 UTC, OhataKenji commented
わかりました。
/2017　への移行作業します。

来年度からは更新しやすいように
2019年分は　2019/　とかに極力入れるようにして
index.htmlから飛ばすようにして良いでしょうか？

2019-10-05 08:13 UTC, OhataKenji commented
![Screenshot from 2019-10-05 17-06-50](https://user-images.githubusercontent.com/11045367/66252146-c5b92f00-e792-11e9-86a2-dd25bdd92f74.png)
![Screenshot from 2019-10-05 17-09-53](https://user-images.githubusercontent.com/11045367/66252169-192b7d00-e793-11e9-885c-ac38b99f8d63.png)
![Screenshot from 2019-10-05 17-10-17](https://user-images.githubusercontent.com/11045367/66252172-1df03100-e793-11e9-9d6a-1ae2542ca6bd.png)
![Screenshot from 2019-10-05 17-10-35](https://user-images.githubusercontent.com/11045367/66252175-23e61200-e793-11e9-8de1-3075dd6fe820.png)


動いてはいます.
あとはソフトの紹介とセキュリティやりますを削除しようと思います.
できればヘッダ画像の変更したいです.

2019-10-05 08:30 UTC, matsubara0507 commented
> /2017　への移行作業します。

このブランチでやる？

> index.htmlから飛ばすようにして良いでしょうか？

ええと思う

動いてるのおk

2019-10-05 08:38 UTC, OhataKenji commented
>>/2017　への移行作業します。
>このブランチでやる？

これは別ブランチでやろうと思います

2019-10-05 08:51 UTC, matsubara0507 approved these changes
@atpons がリクエストチェンジしてるけど

2019-10-05 09:07 UTC, atpons approved these changes

2019-10-05 09:20 UTC, merged